name: safesplit-node

services:
  safesplit-node:
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    image: safesplit-node
    container_name: safesplit-node
    restart: unless-stopped
    environment:
      NODE_RPC_URL: http://host.docker.internal:49545
      NODE_DEPLOYMENT_PATH: /app/deployments/deployment.json
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - 49170:8081
    volumes:
      - .:/app                                          # live source for Air
      - safesplit-node-gomod:/go/pkg/mod                # cache Go modules
      - ../blockchain/deployments:/app/deployments:ro

volumes:
  safesplit-node-gomod:
